set_property PACKAGE_PIN H9 [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property PACKAGE_PIN G9 [get_ports SYSCLK_N]
set_property IOSTANDARD LVDS [get_ports SYSCLK_N]
#set_property PACKAGE_PIN H9 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name SYSCLK_P -period 5.00 -waveform {0 2.5} [get_ports SYSCLK_P]

set_property PACKAGE_PIN Y21 [get_ports led[0]]
set_property IOSTANDARD LVCMOS25 [get_ports led[0]]
set_property PACKAGE_PIN G2 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
set_property PACKAGE_PIN W21 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[2]}]
set_property PACKAGE_PIN A17 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]

set_property PACKAGE_PIN AK25 [get_ports {btn[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {btn[0]}]
set_property PACKAGE_PIN K15 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn[1]}]
#set_property PACKAGE_PIN R27 [get_ports {btn[2]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {btn[2]}]

set_property PACKAGE_PIN AJ13 [get_ports {hsw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hsw[3]}]
set_property PACKAGE_PIN AC17 [get_ports {hsw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hsw[2]}]
set_property PACKAGE_PIN AC16 [get_ports {hsw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hsw[1]}]
set_property PACKAGE_PIN AB17 [get_ports {hsw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hsw[0]}]
